[project]
name = "devops-qa-project"
version = "0.1.0"
description = "DevOps QA project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]",
    "requests",
    "paramiko",
]

[project.scripts]
main = "main:app"
